/**
 * Threads a value through a sequence of functions left-to-right.
 *
 * Combined with operators like `map`, `mapErr`, `match`, etc., this is the
 * primary way to build Result transformation pipelines.
 *
 * @example
 * ```ts
 * import * as R from "@skyr/result";
 *
 * const message = R.pipe(
 *   validateEmail("user@example.com"),
 *   R.map(email => email.toLowerCase()),
 *   R.map(email => `Welcome, ${email}!`),
 *   R.match({
 *     ok: greeting => greeting,
 *     err: e => `Error: ${e.message}`,
 *   }),
 * );
 * ```
 */
export const pipe: {
	<A>(initial: A): A;
	<A, B>(initial: A, ab: (a: A) => B): B;
	<A, B, C>(initial: A, ab: (a: A) => B, bc: (b: B) => C): C;
	<A, B, C, D>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
	): D;
	<A, B, C, D, E>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
	): E;
	<A, B, C, D, E, F>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
	): F;
	<A, B, C, D, E, F, G>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
	): G;
	<A, B, C, D, E, F, G, H>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
	): H;
	<A, B, C, D, E, F, G, H, I>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
	): I;
	<A, B, C, D, E, F, G, H, I, J>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
	): J;
	<A, B, C, D, E, F, G, H, I, J, K>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
	): K;
	<A, B, C, D, E, F, G, H, I, J, K, L>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
	): L;
	<A, B, C, D, E, F, G, H, I, J, K, L, M>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
	): M;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
	): N;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
	): O;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
	): P;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
	): Q;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
	): R;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
	): S;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
	): T;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
	): U;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
		uv: (u: U) => V,
	): V;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
		uv: (u: U) => V,
		vw: (v: V) => W,
	): W;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
		uv: (u: U) => V,
		vw: (v: V) => W,
		wx: (w: W) => X,
	): X;
	<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
		uv: (u: U) => V,
		vw: (v: V) => W,
		wx: (w: W) => X,
		xy: (x: X) => Y,
	): Y;
	<
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,
	>(
		initial: A,
		ab: (a: A) => B,
		bc: (b: B) => C,
		cd: (c: C) => D,
		de: (d: D) => E,
		ef: (e: E) => F,
		fg: (f: F) => G,
		gh: (g: G) => H,
		hi: (h: H) => I,
		ij: (i: I) => J,
		jk: (j: J) => K,
		kl: (k: K) => L,
		lm: (l: L) => M,
		mn: (m: M) => N,
		no: (n: N) => O,
		op: (o: O) => P,
		pq: (p: P) => Q,
		qr: (q: Q) => R,
		rs: (r: R) => S,
		st: (s: S) => T,
		tu: (t: T) => U,
		uv: (u: U) => V,
		vw: (v: V) => W,
		wx: (w: W) => X,
		xy: (x: X) => Y,
		yz: (y: Y) => Z,
	): Z;
} = (initial: unknown, ...fns: ((a: unknown) => unknown)[]) => {
	let curr = initial;
	for (const f of fns) {
		curr = f(curr);
	}
	return curr;
};
